### ISSUE TITLE
Roadmap 4.0

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-trueurl#8]
- [x] Button "Automatische Vererbung des Seitenalias prüfen und aktivieren" entfernen (letzter Button in der Seitenstruktur)
- [x] "Nur Seitenalias zeigen" usw. in die Einstellungen des Benutzers
- [x] "Seiten regenerieren" auf root-relations umstellen
- [x] "Seitenalias reparieren" in die Systemwartung
- [x] Umstellung auf Slug-Generator
- [x] "Vererbung des Startpunkt-Alias" standardmäßig auf "Niemals"
- [x] "Standardmäßig die Alias-Vererbung aktivieren" standardmäßig aktiv
- ~Einstellungen bei Experten-Einstellungen werden beibehalten ggfs. Umstellung auf Symfony-Routen~
- [x] alle Einstellungen unter "Routing"
